modLoader="javafml"
loaderVersion="[31,)"
license="GPL v3"

[[mods]]
    modId="vivecraftforgeextensions"
    version="1.3.0"
    displayName="Vivecraft Forge Extensions"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/vivecraft-forge-extensions"
    logoFile="logo.png"
    authors="Techjar"
    description="Forge companion mod for Vivecraft which handles packets and modifies base code for VR players."

[[dependencies.vivecraftforgeextensions]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vivecraftforgeextensions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
